// based on https://www.lookuptables.com/text/ebcdic
import type { ILookupTable } from "../interface/lookupTableInterface.ts";

export const cp037: ILookupTable[] = [
    { hex: '00', dec: 0, char: 'NUL', desc: 'CONTROL CHAR - Null' },
    { hex: '01', dec: 1, char: 'SOH', desc: 'CONTROL CHAR - Start Of Heading' },
    { hex: '02', dec: 2, char: 'STX', desc: 'CONTROL CHAR - Start of TeXt' },
    { hex: '03', dec: 3, char: 'ETX', desc: 'CONTROL CHAR - End of TeXt' },
    { hex: '04', dec: 4, char: 'PF', desc: 'CONTROL CHAR - Punch ofF' },
    { hex: '05', dec: 5, char: 'HT', desc: 'CONTROL CHAR - Horizontal Tab' },
    { hex: '06', dec: 6, char: 'LC', desc: 'CONTROL CHAR - Lower Case' },
    { hex: '07', dec: 7, char: 'DEL', desc: 'CONTROL CHAR - DELete' },
    { hex: '0A', dec: 10, char: 'SMM', desc: 'CONTROL CHAR - Start of Manual Message' },
    { hex: '0B', dec: 11, char: 'VT', desc: 'CONTROL CHAR - Vertical Tab' },
    { hex: '0C', dec: 12, char: 'FF', desc: 'CONTROL CHAR - Form Feed' },
    { hex: '0D', dec: 13, char: 'CR', desc: 'CONTROL CHAR - Carriage Return' },
    { hex: '0E', dec: 14, char: 'SO', desc: 'CONTROL CHAR - Shift Out' },
    { hex: '0F', dec: 15, char: 'SI', desc: 'CONTROL CHAR - Shift In' },
    { hex: '10', dec: 16, char: 'DLE', desc: 'CONTROL CHAR - Data Link Escape' },
    { hex: '11', dec: 17, char: 'DC1', desc: 'CONTROL CHAR - Device Control 1' },
    { hex: '12', dec: 18, char: 'DC2', desc: 'CONTROL CHAR - Device Control 2' },
    { hex: '13', dec: 19, char: 'TM', desc: 'CONTROL CHAR - Tape Mark' },
    { hex: '14', dec: 20, char: 'RES', desc: 'CONTROL CHAR - REStore' },
    { hex: '15', dec: 21, char: 'NL', desc: 'CONTROL CHAR - New Line' },
    { hex: '16', dec: 22, char: 'BS', desc: 'CONTROL CHAR - BackSpace' },
    { hex: '17', dec: 23, char: 'IL', desc: 'CONTROL CHAR - IdLe' },
    { hex: '18', dec: 24, char: 'CAN', desc: 'CONTROL CHAR - CANcel' },
    { hex: '19', dec: 25, char: 'EM', desc: 'CONTROL CHAR - End of Medium' },
    { hex: '1A', dec: 26, char: 'CC', desc: 'CONTROL CHAR - Cursor Control' },
    { hex: '1B', dec: 27, char: 'CU1', desc: 'CONTROL CHAR - Customer User 1' },
    { hex: '1C', dec: 28, char: 'IFS', desc: 'CONTROL CHAR - Interchange File Separator' },
    { hex: '1D', dec: 29, char: 'IGS', desc: 'CONTROL CHAR - Interchange Goup Separator' },
    { hex: '1E', dec: 30, char: 'IRS', desc: 'CONTROL CHAR - Interchange Record Separator' },
    { hex: '1F', dec: 31, char: 'IUS', desc: 'CONTROL CHAR - Interchange Unit Separator' },
    { hex: '20', dec: 32, char: 'DS', desc: 'CONTROL CHAR - Digit Select' },
    { hex: '21', dec: 33, char: 'SOS', desc: 'CONTROL CHAR - Start Of Significance' },
    { hex: '22', dec: 34, char: 'FS', desc: 'CONTROL CHAR - Field Separator' },
    { hex: '24', dec: 36, char: 'BYP', desc: 'CONTROL CHAR - BYPass' },
    { hex: '25', dec: 37, char: 'LF', desc: 'CONTROL CHAR - Line Feed' },
    { hex: '26', dec: 38, char: 'ETB', desc: 'CONTROL CHAR - End of Tranmission Block' },
    { hex: '27', dec: 39, char: 'ESC', desc: 'CONTROL CHAR - ESCape' },
    { hex: '2A', dec: 42, char: 'SM', desc: 'CONTROL CHAR - Set Mode' },
    { hex: '2B', dec: 43, char: 'CU2', desc: 'CONTROL CHAR - Customer User 2' },
    { hex: '2D', dec: 45, char: 'ENQ', desc: 'CONTROL CHAR - ENQuiry' },
    { hex: '2E', dec: 46, char: 'ACK', desc: 'CONTROL CHAR - ACKnowledge' },
    { hex: '2F', dec: 47, char: 'BEL', desc: 'CONTROL CHAR - BELl' },
    { hex: '32', dec: 50, char: 'SYN', desc: 'CONTROL CHAR - SYNchronous idle' },
    { hex: '34', dec: 52, char: 'PN', desc: 'CONTROL CHAR - Punch oN' },
    { hex: '35', dec: 53, char: 'RS', desc: 'CONTROL CHAR - Reader Stop' },
    { hex: '36', dec: 54, char: 'UC', desc: 'CONTROL CHAR - Upper Case' },
    { hex: '37', dec: 55, char: 'EOT', desc: 'CONTROL CHAR - End of Transmission' },
    { hex: '3B', dec: 59, char: 'CU3', desc: 'CONTROL CHAR - Customer Use 3' },
    { hex: '3C', dec: 60, char: 'DC4', desc: 'CONTROL CHAR - Device Control 4' },
    { hex: '3D', dec: 61, char: 'NAK', desc: 'CONTROL CHAR - Negative AcKnowledge' },
    { hex: '3F', dec: 63, char: 'SUB', desc: 'CONTROL CHAR - Substitute' },
    { hex: '40', dec: 64, char: ' ', desc: 'Space' },
    { hex: '4A', dec: 74, char: '[', desc: 'Left Square Bracket' },
    { hex: '4B', dec: 75, char: '.', desc: 'Full stop' },
    { hex: '4C', dec: 76, char: '<', desc: 'Less-than sign' },
    { hex: '4D', dec: 77, char: '(', desc: 'Left Parenthesis' },
    { hex: '4E', dec: 78, char: '+', desc: 'Plus sign' },
    { hex: '4F', dec: 79, char: '!', desc: 'Exclamation Mark' },
    { hex: '50', dec: 80, char: '&', desc: 'Ampersand' },
    { hex: '5A', dec: 90, char: ']', desc: 'Right Square Bracket' },
    { hex: '5B', dec: 91, char: '$', desc: 'Dollar Sign' },
    { hex: '5C', dec: 92, char: '*', desc: 'Asterisk' },
    { hex: '5D', dec: 93, char: ')', desc: 'Right Parenthesis' },
    { hex: '5E', dec: 94, char: ';', desc: 'Semicolon' },
    { hex: '5F', dec: 95, char: '^', desc: 'Circumflex accent' },
    { hex: '60', dec: 96, char: '-', desc: 'Hyphen-minus' },
    { hex: '61', dec: 97, char: '/', desc: 'Slash' },
    { hex: '6A', dec: 106, char: '|', desc: 'Vertical bar' },
    { hex: '6B', dec: 107, char: ',', desc: 'Comma' },
    { hex: '6C', dec: 108, char: '%', desc: 'Percent Sign' },
    { hex: '6D', dec: 109, char: '_', desc: 'Low line' },
    { hex: '6E', dec: 110, char: '>', desc: 'Greater-than sign' },
    { hex: '6F', dec: 111, char: '?', desc: 'Question mark' },
    { hex: '79', dec: 121, char: '`', desc: 'Grave accent' },
    { hex: '7A', dec: 122, char: ':', desc: 'Colon' },
    { hex: '7B', dec: 123, char: '#', desc: 'Pound Sign' },
    { hex: '7C', dec: 124, char: '@', desc: 'At sign' },
    { hex: '7D', dec: 125, char: "'", desc: 'Apostrophe' },
    { hex: '7E', dec: 126, char: '=', desc: 'Equal sign' },
    { hex: '7F', dec: 127, char: '"', desc: 'Quotation Mark' },
    { hex: '81', dec: 129, char: 'a', desc: 'Latin Small Letter a' },
    { hex: '82', dec: 130, char: 'b', desc: 'Latin Small Letter b' },
    { hex: '83', dec: 131, char: 'c', desc: 'Latin Small Letter c' },
    { hex: '84', dec: 132, char: 'd', desc: 'Latin Small Letter d' },
    { hex: '85', dec: 133, char: 'e', desc: 'Latin Small Letter e' },
    { hex: '86', dec: 134, char: 'f', desc: 'Latin Small Letter f' },
    { hex: '87', dec: 135, char: 'g', desc: 'Latin Small Letter g' },
    { hex: '88', dec: 136, char: 'h', desc: 'Latin Small Letter h' },
    { hex: '89', dec: 137, char: 'i', desc: 'Latin Small Letter i' },
    { hex: '91', dec: 145, char: 'j', desc: 'Latin Small Letter j' },
    { hex: '92', dec: 146, char: 'k', desc: 'Latin Small Letter k' },
    { hex: '93', dec: 147, char: 'l', desc: 'Latin Small Letter l' },
    { hex: '94', dec: 148, char: 'm', desc: 'Latin Small Letter m' },
    { hex: '95', dec: 149, char: 'n', desc: 'Latin Small Letter n' },
    { hex: '96', dec: 150, char: 'o', desc: 'Latin Small Letter o' },
    { hex: '97', dec: 151, char: 'p', desc: 'Latin Small Letter p' },
    { hex: '98', dec: 152, char: 'q', desc: 'Latin Small Letter q' },
    { hex: '99', dec: 153, char: 'r', desc: 'Latin Small Letter r' },
    { hex: 'A1', dec: 161, char: '~', desc: 'Tilde' },
    { hex: 'A2', dec: 162, char: 's', desc: 'Latin Small Letter s' },
    { hex: 'A3', dec: 163, char: 't', desc: 'Latin Small Letter t' },
    { hex: 'A4', dec: 164, char: 'u', desc: 'Latin Small Letter u' },
    { hex: 'A5', dec: 165, char: 'v', desc: 'Latin Small Letter v' },
    { hex: 'A6', dec: 166, char: 'w', desc: 'Latin Small Letter w' },
    { hex: 'A7', dec: 167, char: 'x', desc: 'Latin Small Letter x' },
    { hex: 'A8', dec: 168, char: 'y', desc: 'Latin Small Letter y' },
    { hex: 'A9', dec: 169, char: 'z', desc: 'Latin Small Letter z' },
    { hex: 'C0', dec: 192, char: '{', desc: 'Left Curly Bracket' },
    { hex: 'C1', dec: 193, char: 'A', desc: 'Latin Capital letter A' },
    { hex: 'C2', dec: 194, char: 'B', desc: 'Latin Capital letter B' },
    { hex: 'C3', dec: 195, char: 'C', desc: 'Latin Capital letter C' },
    { hex: 'C4', dec: 196, char: 'D', desc: 'Latin Capital letter D' },
    { hex: 'C5', dec: 197, char: 'E', desc: 'Latin Capital letter E' },
    { hex: 'C6', dec: 198, char: 'F', desc: 'Latin Capital letter F' },
    { hex: 'C7', dec: 199, char: 'G', desc: 'Latin Capital letter G' },
    { hex: 'C8', dec: 200, char: 'H', desc: 'Latin Capital letter H' },
    { hex: 'C9', dec: 201, char: 'I', desc: 'Latin Capital letter I' },
    { hex: 'D0', dec: 208, char: '}', desc: 'Right Curly Bracket' },
    { hex: 'D1', dec: 209, char: 'J', desc: 'Latin Capital letter J' },
    { hex: 'D2', dec: 210, char: 'K', desc: 'Latin Capital letter K' },
    { hex: 'D3', dec: 211, char: 'L', desc: 'Latin Capital letter L' },
    { hex: 'D4', dec: 212, char: 'M', desc: 'Latin Capital letter M' },
    { hex: 'D5', dec: 213, char: 'N', desc: 'Latin Capital letter N' },
    { hex: 'D6', dec: 214, char: 'O', desc: 'Latin Capital letter O' },
    { hex: 'D7', dec: 215, char: 'P', desc: 'Latin Capital letter P' },
    { hex: 'D8', dec: 216, char: 'Q', desc: 'Latin Capital letter Q' },
    { hex: 'D9', dec: 217, char: 'R', desc: 'Latin Capital letter R' },
    { hex: 'E0', dec: 224, char: '\\', desc: 'Backslash' },
    { hex: 'E2', dec: 226, char: 'S', desc: 'Latin Capital letter S' },
    { hex: 'E3', dec: 227, char: 'T', desc: 'Latin Capital letter T' },
    { hex: 'E4', dec: 228, char: 'U', desc: 'Latin Capital letter U' },
    { hex: 'E5', dec: 229, char: 'V', desc: 'Latin Capital letter V' },
    { hex: 'E6', dec: 230, char: 'W', desc: 'Latin Capital letter W' },
    { hex: 'E7', dec: 231, char: 'X', desc: 'Latin Capital letter X' },
    { hex: 'E8', dec: 232, char: 'Y', desc: 'Latin Capital letter Y' },
    { hex: 'E9', dec: 233, char: 'Z', desc: 'Latin Capital letter Z' },
    { hex: 'F0', dec: 240, char: '0', desc: 'Digit Zero' },
    { hex: 'F1', dec: 241, char: '1', desc: 'Digit One' },
    { hex: 'F2', dec: 242, char: '2', desc: 'Digit Two' },
    { hex: 'F3', dec: 243, char: '3', desc: 'Digit Three' },
    { hex: 'F4', dec: 244, char: '4', desc: 'Digit Four' },
    { hex: 'F5', dec: 245, char: '5', desc: 'Digit Five' },
    { hex: 'F6', dec: 246, char: '6', desc: 'Digit Six' },
    { hex: 'F7', dec: 247, char: '7', desc: 'Digit Seven' },
    { hex: 'F8', dec: 248, char: '8', desc: 'Digit Eight' },
    { hex: 'F9', dec: 249, char: '9', desc: 'Digit Nine' }
];
